### ISSUE TITLE
Version 4.0.0 requires  java 9

### ISSUE THREAD

**Issue by michalre** [remondis-it/remap#53]
remap 4.0.0 pulls asm 6.0 jar which is in java 9 format:
[DEBUG]    com.remondis:remap:jar:4.0.0:compile
[DEBUG]       cglib:cglib:jar:3.2.6:compile
[DEBUG]          org.ow2.asm:asm:jar:6.0:compile

This is causing problems with other tools in our build pipeline, so I just wanted to ask whether java 9 is an official requirement.

**Comment by schuettec** [comment]
This is a transitive dependency:
```
ReMap
\--- cglib:cglib:3.2.6
     +--- org.ow2.asm:asm:6.0
```
I do not know if the `org.ow2.asm:asm:6.0` dependency could be workarounded since ReMap relies on cglib. Can you provide more information what's the problem with the Java 9 format?

An official requirement does not exists, but we want to support Java 9 to be able to migrate our systems to Java 9. The only issue related to Java 9 was a request to provide a stable Java 9 module name.

**Comment by michalre** [comment]
We have older version of ProGuard that does not support Java 9 format

**Comment by schuettec** [comment]
How about upgrading ProGuard? ;-)

If thats not suitable for you, you can try to exclude the ASM library and include `org.ow2.asm:asm:5.2` instead. ASM 5.3 is in Java 8 format and ReMap seems to work with ASM 5.2, at least all the tests are ok (no guarantees).

If you are using gradle try
```
  compile('com.remondis:remap:4.0.0') {
    exclude group: 'org.ow2', module: 'asm'
  }
  compile "org.ow2.asm:asm:5.2"
```

**Comment by michalre** [comment]
yeah, upgrading the ProGuard is the right way to go. Thanks for the workaround I will try it until we can upgrade ProGuard

**Comment by michalre** [comment]
When asm jar is excluded from maven dependencies there is an exception when deploying the war to tomcat, so instead I excluded asm jar from proguard processing in proguard maven plugin and everything works fine. Thanks for the help.
